name: Update submodule ref
on: push
env:
  superviser_repo: Gotfrid/project-supervisor
jobs:
  update_submodule_ref:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Update submodule ref
        uses: Gotfrid/project-supervisor/actions/update-submodule-ref@main
        with:
          child: ${{ github.event.repository.name }}
          token: ${{ secrets.PAT }}
